feat(#14): View Game
HE-Arc/SousMot pull request #31
Opened 2022-04-06 08:38 UTC by MassimoFerro

![image](https://user-images.githubusercontent.com/24223196/161932795-42089c34-8159-4eca-ab5f-b7e21c6ec317.png)

Create a view to handle the game

2022-04-06 08:42 UTC, MassimoFerro commented
Sorry, i didn't realize that i formatted `main.scss` by accident :cry:

2022-04-06 08:49 UTC, Narekushia commented
> Sorry, i didn't realize that i formatted `main.scss` by accident cry

Change your IDE settings and recommit, because the indentation changed from 4 spaces to 2 !!! :triumph:

2022-04-06 08:55 UTC, MassimoFerro commented
> > Sorry, i didn't realize that i formatted `main.scss` by accident cry
> 
> Change your IDE settings and recommit, because the indentation changed from 4 spaces to 2 !!! angry angry angry angry

Done, i don't know why my scss indent settings was 2 :thinking:

2022-04-07 14:07 UTC, Narekushia requested changes
Partial review of your code (without the `game.js`) (waiting for you to comment your code :wink: )

I made some suggestions, feel free to check them and if you want, accept them. :heavy_check_mark: 

Another thing, it could be cool to make the page responsive, because on mobile (iPhone 6S), the table and the keyboard can't be displayed at the same time :wink:

2022-04-07 14:07 UTC, Narekushia commented on sousmot/sousmotapp/templates/sousmotapp/game.html
> +{% block title %}Home{% endblock %}
```suggestion
{% block title %}Game{% endblock %}
```

2022-04-07 14:07 UTC, Narekushia commented on sousmot/sousmotapp/templates/sousmotapp/game.html
> +            <p class="subtitle"> {{ mode }}</p>
```suggestion
            <p class="subtitle">{{ mode }}</p>
```

2022-04-07 14:07 UTC, Narekushia commented on sousmot/sousmotapp/templates/sousmotapp/game.html
> +            <p id="timer" class="subtitle"></p>
```suggestion
            <p id="timer" class="subtitle">00:08</p>
```
Maybe add something for the start of the game before the JS is loaded ?

2022-04-07 14:07 UTC, Narekushia commented on sousmot/sousmotapp/static/scss/main.scss
> +    border-radius: 6px;
```suggestion
    border-radius: 6px;
    display:inline-flex;
    justify-content: center;
    align-items: center;
```

To correct the fact that the letter is not centered on mobile

2022-04-07 14:07 UTC, Narekushia commented on sousmot/sousmotapp/static/scss/main.scss
> +    color: white;
```suggestion
    color: $text;
```
Maybe use the same color has the text ?

2022-04-07 14:07 UTC, Narekushia commented on sousmot/sousmotapp/static/scss/main.scss
> +    color: white;
```suggestion
    color: $text;
```

2022-04-07 16:10 UTC, Narekushia reviewed
Also :
- Delete the word when you start typing
- If the letter you type is the same as the first letter, doesn't display it

2022-04-07 16:10 UTC, Narekushia commented on sousmot/sousmotapp/static/js/game.js
> +    if ("ABCDEFGHIJKLMNOPQRSTUVWXYZ".includes(letter)) {
```suggestion
    if ("ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").includes(letter)) {
```
To prevent the catch of multiple "word" like `TUV` or `DEF`

2022-04-07 16:10 UTC, Narekushia commented on sousmot/sousmotapp/static/js/game.js
> +    let letter = event.key;
Why the variable ? :thinking:

2022-04-07 16:10 UTC, Narekushia commented on sousmot/sousmotapp/static/js/game.js
> +let userPosition = 1; // correspond to grid.y
If they correspond to grid.x and grid.y, why do you not call them `grid.x` and `grid.y` ?
The comment is also incorrect ! `grid.x` is `userPosition` and `grid.y` is `userTry`.

```js
let grid = {
    x: 0,
    y: 1
}
```
:wink:

2022-04-07 16:10 UTC, Narekushia commented on sousmot/sousmotapp/static/js/game.js
> +let countDownDate = new Date(end_time * 1000).getTime(); // Date to the end of countdown
```suggestion
const countDownDate = new Date(end_time * 1000).getTime(); // Date to the end of countdown
```
Maybe ?

2022-04-08 23:00 UTC, MassimoFerro commented
@Narekushia 

Thanks for your review.

I improved the code a little bit. I also made the page a bit responsive. I have a problem with the keyboard display with safari, I can't reduce the size of the buttons. 

If I check with the inspector of firefox and it works, do you have an idea?
![Screen Shot 2022-04-09 at 00 56 30](https://user-images.githubusercontent.com/24223196/162544235-c65f7adb-f2d8-439a-9db7-521973d80ae9.png)
![image](https://user-images.githubusercontent.com/24223196/162544464-cab597a7-5af6-4173-8442-b281792ca055.png)

2022-04-10 10:44 UTC, Narekushia commented
> @Narekushia
> 
> Thanks for your review.
> 
> I improved the code a little bit. I also made the page a bit responsive. I have a problem with the keyboard display with safari, I can't reduce the size of the buttons.
> 
> If I check with the inspector of firefox and it works, do you have an idea? ![Screen Shot 2022-04-09 at 00 56 30](https://user-images.githubusercontent.com/24223196/162544235-c65f7adb-f2d8-439a-9db7-521973d80ae9.png) ![image](https://user-images.githubusercontent.com/24223196/162544464-cab597a7-5af6-4173-8442-b281792ca055.png)

I played a bit with Safari iOS (13.5.1) and it's definitly because of the padding, adding `padding: 0` to the button solves the issue. 
But on my device, the keyboard still cut... (the letter P has its own line). I think we need to reduce the margin between the button when on mobile (like Sutom do) to have a proper keyboard. I modified the div containing the button to `display: flex` and it worked, but then we need to add margin when on desktop.

2022-04-11 08:34 UTC, Narekushia reviewed
I love nitpicking, so here some things you can change :smile:

2022-04-11 08:34 UTC, Narekushia commented on sousmot/sousmotapp/static/scss/main.scss
> +}
```suggestion
.table {
    display: inline;
    
    td {
        padding: 0.5rem;
        color: $text;
        font-size: 2rem;
        font-weight: bold;
        background-color: $navbar-background-color;
        
        div {
            width: 50px;
            height: 50px;
            overflow: hidden;

            @include mobile {
                width: 35px;
                height: 35px;
                font-size: 1.5rem;
            }
        }
    }
}
```
You can use the SCSS syntax :wink:

2022-04-11 08:34 UTC, Narekushia commented on sousmot/sousmotapp/static/scss/main.scss
> +}
```suggestion
    @include mobile {
        width: 2rem;
    }

    &:hover {
        background-color: $navbar-item-hover-background-color;
        cursor: pointer;
    }
}
```
SCSS Syntax :wink:

2022-04-11 08:34 UTC, Narekushia commented on sousmot/sousmotapp/templates/sousmotapp/game.html
> +        let end_time = {{ end_time }};
```suggestion
        const wordLength = {{ word_length_js }};
        const wordFirstLetter = '{{ word_first_letter }}';

        const end_time = {{ end_time }};
```
Maybe you can use `const` here ? :thinking:

2022-04-11 08:35 UTC, Narekushia commented
So yeah, apart from the keyboard on smartphone (specifically iOS), it seems to be good for me :+1:

2022-04-11 08:50 UTC, Narekushia approved these changes

2022-04-11 08:50 UTC, merged